-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\BoxcarAveragerFixedPointPublish\Detect_Rise_Positive.vhd
-- Created: 2024-10-21 19:53:33
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Detect_Rise_Positive
-- Source Path: BoxcarAveragerFixedPointPublish/DSP/Detect Rise Positive
-- Hierarchy Level: 1
-- Model version: 6.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Detect_Rise_Positive IS
  PORT( Clk                               :   IN    std_logic;
        Reset                             :   IN    std_logic;
        U                                 :   IN    signed(16 DOWNTO 0);  -- sfix17
        Y                                 :   OUT   std_logic
        );
END Detect_Rise_Positive;


ARCHITECTURE rtl OF Detect_Rise_Positive IS

  -- Component Declarations
  COMPONENT Positive_rsvd
    PORT( u                               :   IN    signed(16 DOWNTO 0);  -- sfix17
          y                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Positive_rsvd
    USE ENTITY work.Positive_rsvd(rtl);

  -- Signals
  SIGNAL U_k                              : std_logic;
  SIGNAL U_k_1                            : std_logic;
  SIGNAL FixPt_Relational_Operator_relop1 : std_logic;

BEGIN
  -- U(k)
  -- Edge

  u_Positive : Positive_rsvd
    PORT MAP( u => U,  -- sfix17
              y => U_k
              );

  -- Store in Global RAM
  Delay_Input1_process : PROCESS (Clk)
  BEGIN
    IF Clk'EVENT AND Clk = '1' THEN
      IF Reset = '1' THEN
        U_k_1 <= '0';
      ELSE 
        U_k_1 <= U_k;
      END IF;
    END IF;
  END PROCESS Delay_Input1_process;


  
  FixPt_Relational_Operator_relop1 <= '1' WHEN U_k > U_k_1 ELSE
      '0';

  Y <= FixPt_Relational_Operator_relop1;

END rtl;

