-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\BoxcarAveragerFixedPointPublish\DSP_pkg.vhd
-- Created: 2024-10-21 19:53:33
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE DSP_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
  TYPE vector_of_signed80 IS ARRAY (NATURAL RANGE <>) OF signed(79 DOWNTO 0);
END DSP_pkg;

